### ISSUE TITLE
Requirements do not auto-install

### ISSUE THREAD

**Issue by stuartspotlight** [SpotlightData/nanowire-plugin-py#3]
When pip installing nanowire-plugin the requirements do not get automatically installed

**Comment by Southclaws** [comment]
Check out [pipenv](https://docs.pipenv.org/) for much nicer Python dependency management :)

**Comment by stuartspotlight** [comment]
I fixed this by adding the line "install_requires=["minio", "pika"]," to the setup.py setup command. It seems to be working now. Does pipenv handle the creation of sub modules?

**Comment by Southclaws** [comment]
pipenv is like a complete replacement for the requirements.txt and setup.py stuff, not sure about the _creation_ of sub modules but that's a standard python feature anyway so it'll play well with it.

**Comment by stuartspotlight** [comment]
Requirements will now autoinstall due to:-
```
install_requires=["minio", "pika"]
```
